config/routes.rb
School::Application.routes.draw do
  get "report/teams"

  root :to => 'students#index'
  resources :teams
  resources :subjects
  resources :students
  resources :teachers
  resources :lessons

end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  attr_accessible :team_id, :teacher_id, :subject_id
  belongs_to :team
  belongs_to :teacher
  belongs_to :subject
  validates_presence_of :team, :teacher, :subject
end

app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :age, :name, :team_id
  validates_presence_of :name, :team
  belongs_to :team
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  attr_accessible :description, :name
  has_many :lesson
  validates_presence_of :name
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  attr_accessible :age, :name
  validates_presence_of :name
  has_many :lessons
end

app/models/team.rb
class Team < ActiveRecord::Base
  attr_accessible :name
  validates_presence_of :name
  has_many :students
  has_many :lessons
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  respond_to :html

  def index
    @lessons = Lesson.all
    respond_with(@lessons)
  end

  def show
    @lesson = Lesson.find(params[:id])
    respond_with(@lesson)
  end

  def new
    @lesson = Lesson.new
    respond_with(@lesson)
  end

  def create
    @lesson = Lesson.new(params[:lesson])
    if @lesson.save
      flash[:notice] = t('lessons.created')
    end

    respond_with(@lesson, :location => @lesson)
  end

  def edit
    @lesson = Lesson.find(params[:id])
    respond_with @lesson
  end

  def update
    @lesson = Lesson.find(params[:id])

    if @lesson.update_attributes(params[:lesson])
      flash[:notice] = t('lessons.updated')
    end

    respond_with(@lesson, :location => @lesson)
  end

  def destroy
    @lesson = Lesson.find(params[:id])
    @lesson.destroy
    respond_with(nil, :location => teams_path)
  end
end

app/controllers/report_controller.rb
class ReportController < ApplicationController
  def teams
    report = Report.new(params)
    @teams = report.search_teams
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  respond_to :html

  def index
    @students = Student.all
    respond_with @students
  end

  def show
    @student = Student.find(params[:id])
    respond_with @student
  end

  def new
    @student = Student.new
    respond_with @student
  end

  def edit
    @student = Student.find(params[:id])
    respond_with @student
  end

  def create
    @student = Student.new(params[:student])

    if @student.save
      flash[:notice] = t('students.created')
    end

    respond_with(@student, :location => @student)
  end

  def update
    @student = Student.find(params[:id])

    if @student.update_attributes(params[:student])
      flash[:notice] = t('students.updated')
    end

    respond_with(@student, :location => @student)
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy

    respond_with(nil, :location => students_path)
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  respond_to :html

  def index
    @subjects = Subject.all
    respond_with @subjects
  end

  def show
    @subject = Subject.find(params[:id])
    respond_with @subject
  end

  def new
    @subject = Subject.new
    respond_with @subject
  end

  def edit
    @subject = Subject.find(params[:id])
    respond_with @subject
  end

  def create
    @subject = Subject.new(params[:subject])

    if @subject.save
      flash[:notice] = t("subjects.created")
    end
    respond_with(@subject, :location => @subject)
  end

  def update
    @subject = Subject.find(params[:id])

    if @subject.update_attributes(params[:subject])
      flash[:notice] = t("subjects.updated")
    end
    respond_with(@subject, :location => @subject)
  end

  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy

    respond_with(nil, :location => subjects_path)
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  respond_to :html

  def index
    @teachers = Teacher.all
    respond_with @teachers
  end

  def show
    @teacher = Teacher.find(params[:id])
    respond_with @teacher
  end

  def new
    @teacher = Teacher.new
    respond_with @teacher
  end

  def edit
    @teacher = Teacher.find(params[:id])
  end

  def create
    @teacher = Teacher.new(params[:teacher])

    if @teacher.save
      flash[:notice] = t("teachers.created")
    end

    respond_with(@teacher, :location => @teacher)
  end

  def update
    @teacher = Teacher.find(params[:id])

    if @teacher.update_attributes(params[:teacher])
      flash[:notice] = t("teachers.updated")
    end

    respond_with(@teacher, :location => @teacher)
  end

  def destroy
    @teacher = Teacher.find(params[:id])
    @teacher.destroy

    respond_with(nil, :location => teachers_path)
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  respond_to :html

  def index
    @teams = Team.all
    respond_with @teams
  end

  def show
    @team = Team.find(params[:id])
    respond_with @team
  end

  def new
    @team = Team.new
    respond_with @team
  end

  def edit
    @team = Team.find(params[:id])
    respond_with @team
  end

  def create
    @team = Team.new(params[:team])

    if @team.save
      flash[:notice] = t("teams.created")
    end

    respond_with(@team, :location => @team)
  end

  def update
    @team = Team.find(params[:id])

    if @team.update_attributes(params[:team])
      flash[:notice] = t("teams.updated")
    end

    respond_with(@team, :location => @team)
  end

  def destroy
    @team = Team.find(params[:id])
    @team.destroy
    respond_with(nil, :location => teams_path)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>School</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="#">School</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><%= link_to "Home", "/" %></a></li>
              <li class="active"><%= link_to t("activerecord.models.teacher"), teachers_path %></a></li>
              <li class="active"><%= link_to t("activerecord.models.student"), students_path %></li>
              <li class="active"><%= link_to t("activerecord.models.subject"), subjects_path %></li>
              <li class="active"><%= link_to t("activerecord.models.team"), teams_path %></li>
              <li class="active"><%= link_to t("activerecord.models.lesson"), lessons_path %></li>
              <li class="active"><%= link_to t("report"), "/report/teams" %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    <div class="body-container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/lessons/_form.html.erb
<%= form_for(@lesson) do |f| %>
  <% if @lesson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lesson.errors.count, t("error")) %></h2>

      <ul>
      <% @lesson.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :team %><br />
    <%= select("lesson", "team_id", Team.all.collect {|p| [ p.name, p.id ] }) %>
  </div>
  <div class="field">
    <%= f.label :subject %><br />
    <%= select("lesson", "subject_id", Subject.all.collect {|p| [ p.name, p.id ] }) %>
  </div>
  <div class="field">
    <%= f.label :teacher %><br />
    <%= select("lesson", "teacher_id", Teacher.all.collect {|p| [ p.name, p.id ] }) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lessons/edit.html.erb
<h1><%= t("lessons.editing") %></h1>

<%= render 'form' %>

<%= link_to t('show'), @lesson %> |
<%= link_to t('back'), lessons_path %>

app/views/lessons/index.html.erb
<h1><%= t("lessons.listing") %></h1>

<table class="table">
  <tr>
    <th><%= t("activerecord.attributes.lesson.subject") %></th>
    <th><%= t("activerecord.attributes.lesson.teacher") %></th>
    <th><%= t("activerecord.attributes.lesson.team") %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lessons.each do |lesson| %>
  <tr>
    <td><%= lesson.subject.name %></td>
    <td><%= lesson.teacher.name %></td>
    <td><%= lesson.team.name %></td>
    <td><%= link_to t('show'), lesson %></td>
    <td><%= link_to t('edit'), edit_lesson_path(lesson) %></td>
    <td><%= link_to t('destroy'), lesson, method: :delete, data: { confirm: t('are-you-sure') } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to t('new'), new_lesson_path %>

app/views/lessons/new.html.erb
<h1><%= t("activerecord.models.lesson") %></h1>

<%= render 'form' %>

<%= link_to t('back'), lessons_path %>

app/views/lessons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b><%= t("activerecord.attributes.lesson.subject")%>:</b>
  <%= @lesson.subject.name %>
</p>

<p>
  <b><%= t("activerecord.attributes.lesson.teacher")%>:</b>
  <%= @lesson.teacher.name %>
</p>

<p>
  <b><%= t("activerecord.attributes.lesson.team")%>:</b>
  <%= @lesson.team.name %>
</p>

<%= link_to t('edit'), edit_lesson_path(@lesson) %> |
<%= link_to t('back'), lessons_path %>

app/views/report/teams.html.erb
<h1>Relatório das <%= t("teams.listing") %></h1>
<p>Filtrar por: </p>
<form class="form-inline">
  <select name="filter">
    <option value="teacher">Professor</option>
    <option value="team">Turma</option>
  </select>
  <input name="name" type="text" placeholder="Nome">
  <button type="submit">Filtrar</button>
</form>
<% @teams.each do |team| %>
  <strong><%= team.name %></strong><br>
  Alunos:
  <ul>
    <% team.students.each do |student| %>
      <li><%= student.name %></li>
    <% end %>
  </ul>
  Matéria e Professor:
  <ul>
    <% team.lessons.each do |lesson| %>
      <li><%= lesson.subject.name %> - <%= lesson.teacher.name %></li>
    <% end %>
  </ul>
  <hr>
<% end %>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, t("error")) %></h2>

      <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.text_field :age %>
  </div>
  <div class="field">
    <%= f.label :team %><br />
    <%= select("student", "team_id", Team.all.collect {|p| [ p.name, p.id ] }) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1><%= t("students.editing") %></h1>

<%= render 'form' %>

<%= link_to t('show'), @student %> |
<%= link_to t('back'), students_path %>

app/views/students/index.html.erb
<h1><%= t("students.listing") %></h1>

<table class="table">
  <tr>
    <th><%= t("activerecord.attributes.student.name") %></th>
    <th><%= t("activerecord.attributes.student.age") %></th>
    <th><%= t("activerecord.attributes.student.team") %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @students.each do |student| %>
  <tr>
    <td><%= student.name %></td>
    <td><%= student.age %></td>
    <td><%= student.team.name %></td>
    <td><%= link_to t('show'), student %></td>
    <td><%= link_to t('edit'), edit_student_path(student) %></td>
    <td><%= link_to t('destroy'), student, method: :delete, data: { confirm: t('are-you-sure') } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to t('new'), new_student_path %>

app/views/students/new.html.erb
<h1><%= t("activerecord.models.student") %></h1>

<%= render 'form' %>

<%= link_to t('back'), students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b><%= t("activerecord.attributes.student.name")%>:</b>
  <%= @student.name %>
</p>

<p>
  <b><%= t("activerecord.attributes.student.age")%>:</b>
  <%= @student.age %>
</p>

<p>
  <b><%= t("activerecord.attributes.student.team")%>:</b>
  <%= @student.team.name %>
</p>

<%= link_to t('edit'), edit_student_path(@student) %> |
<%= link_to t('back'), students_path %>

app/views/subjects/_form.html.erb
<%= form_for(@subject) do |f| %>
  <% if @subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subject.errors.count, t("error")) %></h2>

      <ul>
      <% @subject.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :rows => 10 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<h1><%= t("subjects.editing") %></h1>

<%= render 'form' %>

<%= link_to t('show'), @subject %> |
<%= link_to t('back'), subjects_path %>

app/views/subjects/index.html.erb
<h1><%= t("subjects.listing") %></h1>

<table class="table">
  <tr>
    <th><%= t("activerecord.attributes.subject.name") %></th>
    <th><%= t("activerecord.attributes.subject.description") %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @subjects.each do |subject| %>
  <tr>
    <td><%= subject.name %></td>
    <td><%= subject.description %></td>
    <td><%= link_to t('show'), subject %></td>
    <td><%= link_to t('edit'), edit_subject_path(subject) %></td>
    <td><%= link_to t('destroy'), subject, method: :delete, data: { confirm: t('are-you-sure') } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to t('new'), new_subject_path %>

app/views/subjects/new.html.erb
<h1><%= t("activerecord.models.subject") %></h1>

<%= render 'form' %>

<%= link_to t('back'), subjects_path %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b><%= t("activerecord.attributes.subject.name") %>:</b>
  <%= @subject.name %>
</p>

<p>
  <b><%= t("activerecord.attributes.subject.description") %>:</b>
  <%= @subject.description %>
</p>


<%= link_to t('edit'), edit_subject_path(@subject) %> |
<%= link_to t('back'), subjects_path %>

app/views/teachers/_form.html.erb
<%= form_for(@teacher) do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, t("error")) %></h2>

      <ul>
      <% @teacher.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.text_field :age %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1><%= t("teachers.editing") %></h1>

<%= render 'form' %>

<%= link_to t('show'), @teacher %> |
<%= link_to t('back'), teachers_path %>

app/views/teachers/index.html.erb
<h1><%= t "teachers.title" %> </h1>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Age</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @teachers.each do |teacher| %>
  <tr>
    <td><%= teacher.name %></td>
    <td><%= teacher.age %></td>
    <td><%= link_to t('show'), teacher %></td>
    <td><%= link_to t('edit'), edit_teacher_path(teacher) %></td>
    <td><%= link_to t('destroy'), teacher, method: :delete, data: { confirm: t("are-you-sure") } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to t('new'), new_teacher_path %>

app/views/teachers/new.html.erb
<h1><%= t("activerecord.models.teacher") %></h1>

<%= render 'form' %>

<%= link_to t('back'), teachers_path %>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b><%= t("activerecord.attributes.teacher.name")%>:</b>
  <%= @teacher.name %>
</p>

<p>
  <b><%= t("activerecord.attributes.teacher.age")%>:</b>
  <%= @teacher.age %>
</p>


<%= link_to t('edit'), edit_teacher_path(@teacher) %> |
<%= link_to t('back'), teachers_path %>